Login page
kuri-team/yabe-online-mall pull request #15
Opened 2021-04-22 12:45 UTC by miketvo

- I kept everything I can for Thu.
- Implemented responsive login page.
- Implemented toggle password visibility button.

2021-04-22 14:15 UTC, rider3458 approved these changes

2021-04-23 10:13 UTC, doanyennhi requested changes
Texts in the fields are hard to read because of their color

2021-04-23 10:13 UTC, doanyennhi commented on public/mall/account/login/index.html
> +    <label><input id="username" type="text" name="username" placeholder="Username / Email" required></label>
Should be Phone Number/ Email according to assignment requirements

2021-04-23 11:19 UTC, doanyennhi approved these changes

2021-04-23 11:50 UTC, merged