Register page
kuri-team/yabe-online-mall pull request #20
Opened 2021-04-24 03:13 UTC by miketvo

This is not Thu's initial design, but I try to incorporate as much of her design philosophy as possible while maintaining our site-wide minimalism and utilizing existing code.

2021-04-24 04:34 UTC, tnathu-ai reviewed
+Missing profile picture (an upload file field)

2021-04-24 05:38 UTC, doanyennhi requested changes
- Should add arrows for select elements
- Missing upload profile picture
- Fields have different lengths when screen size <= 950px

2021-04-24 05:38 UTC, doanyennhi commented on public/mall/account/register/index.html
> +            <label class="label" for="store-category">Business Category</label>
label should be 'Store Category'

2021-04-24 14:36 UTC, rider3458 approved these changes

2021-04-25 08:09 UTC, tnathu-ai approved these changes
Well done!

2021-04-25 08:42 UTC, merged