Feature footer menu dropdown animation
kuri-team/yabe-online-mall pull request #31
Opened 2021-04-27 15:06 UTC by miketvo

Minimal coding for maximum effects

2021-04-27 16:35 UTC, doanyennhi requested changes

2021-04-27 16:35 UTC, doanyennhi commented on public/css/common.css
>  #footer-menu-browse-product:hover ul {
Code lines 740-743 and 746-749 are the same => can combine them

2021-04-28 01:53 UTC, rider3458 approved these changes

2021-04-28 03:58 UTC, doanyennhi approved these changes

2021-04-28 11:17 UTC, merged