update subTotal and totalPrice in localStorage and in page
kuri-team/yabe-online-mall pull request #39
Opened 2021-04-30 15:49 UTC by rider3458

update subTotal and totalPrice in localStorage and in page whenever  a product is added/ is removed/ increases in quantity/ decreases in quantity

2021-04-30 16:02 UTC, miketvo requested changes
Cart Page: Subtotal and total can go to negative values if user continuously click on the "-" button.

2021-05-01 10:08 UTC, doanyennhi requested changes
Should remove add to cart message when clicking on "buy now" button since the transition to cart page is very fast.

2021-05-01 14:51 UTC, miketvo approved these changes

2021-05-01 16:36 UTC, doanyennhi approved these changes

2021-05-01 16:36 UTC, merged