Feature cart coupon
kuri-team/yabe-online-mall pull request #40
Opened 2021-05-02 13:49 UTC by rider3458

coupon "COSC2430-HD" and "COSC2430-DI" can be added to get 20% and 10% discount respectively
applying the wrong coupon code returns an invalid msg
reload page if remove coupon
restyle cart a bit to fit coupon input

2021-05-02 14:29 UTC, miketvo requested changes
- Please use `#ccc5b9` for the "Apply" button background (text color `#403d39`). It is too similar to the "Continue shopping button" at the moment.
- No hover feedback for the "Apply" button. **DO NOT MAKE ME REMIND YOU THIS AGAIN** For the :hover background color, use `#403d39` (text color: `#ccc5b9`).
- USD currency always have two-digit floating point precision (e.g. $12.20, not ~~$12.2~~). Do your research thoroughly, please.

2021-05-03 07:12 UTC, doanyennhi requested changes

2021-05-03 07:12 UTC, doanyennhi commented on public/css/cart.css
> +
Remove extra line here

2021-05-03 07:33 UTC, doanyennhi requested changes

2021-05-03 07:33 UTC, doanyennhi commented on public/mall/cart/index.html
> +                    <label for="insert-coupon"></label>
Should put "Coupon" inside label

2021-05-03 07:38 UTC, miketvo commented on public/mall/cart/index.html
> +                    <label for="insert-coupon"></label>
E.g.
```html
<label for="insert-coupon">Coupon</label>
```

2021-05-03 07:50 UTC, tnathu-ai reviewed
Disable "Order Placement" page to be **unavailable for guests**, 

Change the styling of coupon message, can try mine:
<p class="coupon-msg" **style="margin: -50px 90px;"**>Coupon applied</p>

Add more meaningful message like: **10% discount is applied, 20% discount** is applied instead of “Coupon applied”

Implement function: When the **quantity of a product is updated through the + and - button** below the price (cart page), the total order amount & price needs to be updated automatically.

2021-05-03 14:16 UTC, doanyennhi approved these changes

2021-05-03 20:05 UTC, miketvo approved these changes

2021-05-03 20:09 UTC, merged