Add second product detail page
kuri-team/yabe-online-mall pull request #5
Opened 2021-04-20 17:33 UTC by doanyennhi

- Created a second product detail page, link recommended products to first product detail, fix description to shop name in recommended product cards, changed main product info
- Fixed bad links, renamed images of product detail 2
- Cropped images to 1:1 ratio
- Fixed date format for consistency with other product detail page

2021-04-20 17:37 UTC, miketvo requested changes
Please address these issues

2021-04-20 17:37 UTC, miketvo commented on public/store/store-template/product-detail-2/index.html
> +</html>
Needs newline at end of file

2021-04-20 17:37 UTC, miketvo commented on public/store/store-template/product-detail-2/index.html
> +                        src="../../../media/image/book_cover/heartstopper_cover.jfif"></a>
Wrong file extention

2021-04-20 18:04 UTC, miketvo approved these changes
Looks good to me

2021-04-21 02:22 UTC, rider3458 approved these changes

2021-04-21 02:23 UTC, merged